CREATE DATABASE `belajar_oop` /*!40100 COLLATE 'latin1_swedish_ci' */;

CREATE TABLE `categories` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NOT NULL,
	`slug` VARCHAR(50) NOT NULL,
	`created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
	`updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
	PRIMARY KEY (`id`)
) ENGINE InnoDB;

CREATE TABLE `products` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NOT NULL,
	`slug` VARCHAR(50) NOT NULL,
	`stock` INT NOT NULL,
	`created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
	`updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
	PRIMARY KEY (`id`)
) ENGINE InnoDB;

CREATE TABLE `products` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`category_id` INT NOT NULL,
	`name` VARCHAR(50) NOT NULL,
	`slug` VARCHAR(50) NOT NULL,
	`stock` INT NOT NULL DEFAULT 0,
	`price` DECIMAL(10,0) NOT NULL DEFAULT 0,
	`created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
	`updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
	PRIMARY KEY (`id`),
	INDEX `category_id` (`category_id`)
) ENGINE InnoDB;